### ISSUE TITLE
Showcase this paper on the showyourwork docs?

### ISSUE THREAD

**Issue by rodluger** [TeamLEGWORK/LEGWORK-paper#1]
Hey @TomWagg, would you be interested in showcasing this paper on the [showyourwork documentation](https://showyourwork.readthedocs.io/en/stable/projects/)? It's just a matter of entering the metadata in [this JSON file](https://github.com/rodluger/showyourwork/blob/main/docs/projects.json) via a PR.

**Comment by TomWagg** [comment]
Oh yeah absolutely @rodluger, that sounds great!
